version: 2

jobs:
  checkout_and_compile:
    docker:
      - image: circleci/node:9.6.1
    working_directory: ~/setProtocol.js
    steps:
      - checkout
      - restore_cache:
          key: module-cache-{{ checksum "yarn.lock" }}
      - run: 
          name: Inject Truffle
          command: yarn global add truffle
      - run:
          name: Fetch Dependencies
          command: yarn
      - save_cache:
          key: module-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Transpile
          command: yarn build
      - save_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/setProtocol.js
  test:
    docker:
      - image: circleci/node:9.6.1
    working_directory: ~/setProtocol.js
    parallelism: 2
    steps:
      - restore_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
      - run:
            name: Test RPC
            command: yarn chain
            background: true
      - run:
            name: Jest
            command: |
              mkdir /tmp/test-results
              TEST_FILES="$(circleci tests glob "./test/integration/**/*.spec.ts" | circleci tests split --split-by=timings)"
              yarn test --findRelatedTests ${TEST_FILES}
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results

workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout_and_compile
      - test:
          requires:
            - checkout_and_compile
