version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
        - checkout
        - run:
            name: global installs
            command: yarn global add truffle
        - run: yarn
        - run:
            name: testrpc
            command: yarn chain
            background: true
        - run: sleep 90
        - run: yarn test
